config/routes.rb
CheapNewYork::Application.routes.draw do
  devise_for :users

  resources :sites do
    resources :reviews
  end

  post '/sites/zipsearch', to: 'sites#zipsearch', as: 'sites_zipsearch'

  get '/welcome', to: 'sites#splash'

  root :to => 'sites#index'

end

app/models/review.rb
class Review < ActiveRecord::Base
  attr_accessible :rating, :written_text
  belongs_to :site
  belongs_to :user
end

app/models/site.rb
class Site < ActiveRecord::Base
  attr_accessible :address, :name, :zipcode, :cost, :phone, :city, :yelp, :url
  has_many :reviews
  has_many :users, through: :reviews

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  #SDF: Adding my particular ActiveRecord relationships here
  has_many :reviews
  has_many :sites, through: :reviews

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
#	before_filter :authenticate_user!, :only => [:new] #, except: [:index] 
	before_filter :authenticate_user!, :except => [:show] #, except: [:index] 
	
	def new
		@site = Site.find(params[:site_id])
	end

	def edit
		@site = Site.find(params[:site_id])
		@review = Review.find(params[:id]) 
	end

	def create
		@review = Review.create()
		@review.rating = params[:rating]
		@review.written_text = params[:written_text]
		@review.site_id = params[:site_id]
		@review.user_id = current_user[:id] #session[:current_user_id]
		@review.save
#binding.pry
#		redirect_to site_review_path(params[:site_id], @review)
		redirect_to site_path(params[:site_id])

	end

	def show
		@review = Review.find(params[:id])
	end
	def destroy
		Review.find(params[:id]).destroy
		redirect_to sites_path
	end
	def update
		@review = Review.find(params[:id])
		@review.rating = params[:rating]
		@review.written_text = params[:written_text]
		@review.save
		redirect_to '/'

	end

end

app/controllers/sites_controller.rb
require 'yelp_api' # in the lib folder

class SitesController < ApplicationController	
	def index
		@sites = Site.all
	end

	def new
		@band = Site.new()
	end

	def zipsearch
		@sites = Site.where(:zipcode => params[:zipcode])
		@sites |= YelpApi.searchZip(params[:zipcode])
		session[:zipcode] = params[:zipcode]
	end

	def show
		@site = Site.find(params[:id])
	end	

	def splash
	end
	

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
<% if user_signed_in? %>
	<p class="navbar-brand">Welcome, <%= current_user.email %></p>

  <%= link_to "Logout", destroy_user_session_path, class: 'navbar-brand', method: :delete %>
<% else %>
  <%= link_to "sign-in", new_user_session_path, class: 'navbar-brand' %>
  <%= link_to "sign-up", new_user_registration_path, class: 'navbar-brand' %>
<% end %>


    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<a href="http://www.unhp.org/crg/indy-maps-manhatzip.html" target="_ManhattanZipcodeMap">Manhattan ZipCode Map</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    	<title>CheapNewYork</title>
		<meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Nyc311 Complaints Morning Exercise" %>">
    

	<%= stylesheet_link_tag    "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>

<link href='http://fonts.googleapis.com/css?family=Allan' rel='stylesheet' type='text/css'>

	<script language="javascript" type="text/javascript">
		$(document).ready(function(){$("#myTable").tablesorter();});
	</script>
</head>

<body>
   <header>
      <%= render 'layouts/navigation' %>
    </header>

<!-- This is where Devise alerts a user to their state.  It is here in the 
application.html.erb so that it appears on EVERY page.  The p tags will appear everywhere and be empty UNTIL Devise has something to say, and then that information will be present in these tags -->
<p class=”notice”><%= notice %></p>
<p class=”alert”><%= alert %></p>

<br><br>


    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>

</body>

<footer class="ScooterFooter" >
  <hr>
    <span>Page Design: Scooterlicious, Inc.</span>
</footer>

</html>

app/views/reviews/edit.html.erb
<h1>Edit review</h1>

<table id="myTable" class="table">
	<thead>
		<tr>
			<th class="col-sm-1">Cost</th>
			<th class="col-sm-2">Name</th>
			<th class="col-sm-2">Address</th>
		</tr>
	</thead>
	<tbody>
			<tr>
				<td><%= @site.cost %></td>
				<td><%= @site.name %></td>
				<td><%= @site.address %></td>
			</tr>
			<tr>
				<td></td>
				<td></td>
				<td></td>		
			</tr>
	</tbody>
</table>

<form action="<%= site_review_path(@site, @review) %>" method="post" class="form-horizontal container" role="form" >
	<input name="_method" type="hidden" value="PUT" />
	<label class="control-label" for="language">Rating</label>
	<select class="form-control" name="rating" >
		<option value="1">1 Star</option>
		<% 1.5.step(5,0.5) do |i| %>
		<option value ="<%= i %>"
			<%if (i == @review.rating)%>
			<%=selected="selected"%>
			<%end %>
			><%= i %> Stars
		</option>
		<% end %>
	</select>
	<label class="control-label" for="language">Review text</label>
	<textarea name="written_text" class="form-control" rows="4" cols="50"><%= @review.written_text %></textarea>
	<%= token_tag :authenticity_token %>
	<%= button_to 'Save Changes', site_review_path(@site, @review), :method => :put, :class => "form-control"%>
	</form>

app/views/reviews/new.html.erb
<h1>Create a new review</h1>

<table id="myTable" class="table">
	<thead>
		<tr>
			<th class="col-sm-1">Cost</th>
			<th class="col-sm-2">Name</th>
			<th class="col-sm-2">Address</th>
		</tr>
	</thead>
	<tbody>
			<tr>
				<td><%= @site.cost %></td>
				<td><%= @site.name %></td>
				<td><%= @site.address %></td>
			</tr>
			<tr>
				<td></td>
				<td></td>
				<td></td>
			</tr>
	</tbody>
</table>

<form action="<%= site_reviews_path %>" method="post" class="form-horizontal container" role="form">
	<label class="control-label" for="language">Rating</label>

	<select class="form-control" name="rating" >
		<option value="1">1 Star</option>
		<% 1.5.step(5,0.5) do |i| %>
			<option value ="<%= i %>"><%= i %> Stars</option>
		<% end %>
	</select>
	<label class="control-label" for="language">Review text</label>
	<textarea name="written_text" class="form-control" rows="4" cols="50" placeholder="What did you think?"></textarea>

	<%= token_tag :authenticity_token %>
	<button class="form-control" id="submit">Create Review</button>
</form>

app/views/reviews/show.html.erb
<!-- <div class="row">
 -->	<!-- <div class="col-lg-3 col-md-3 col-sm-3"> -->
		<h1 class="site_name">Your Rating: <%= @review.rating %></h1>

	<!-- </div> -->
<!-- 	<div class="col-lg-9 col-md-3 col-sm-3">
 -->		<h1 class="site_name">Your Review: <%= @review.written_text %></h1>
<!-- 	</div>
 -->
	<a href="/sites">Site index</a>

<!-- </div> -->

app/views/sites/DELETEME.show.html.erb
<br><br><br><br>

SITES SHOW HTML ERB....
<div class="row">
	<div class="col-lg-3 col-md-3 col-sm-3">
		<h1 class="site_name"><%= @site.name %></h1>

		<p>
			Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis, harum maxime dolorem perspiciatis iure quos et esse consectetur obcaecati a architecto quibusdam corporis eos molestiae aspernatur. Eaque corporis vero aperiam!
		</p>
	</div>
	<div class="col-lg-9 col-md-3 col-sm-3">
		<p>
			Lorem ipsum dolor sit amet, consectetur adipisicing elit. Totam, rem, est, provident, doloremque sapiente id vitae voluptate tempora corporis dolorem consectetur incidunt molestiae praesentium aspernatur quas assumenda nobis. Eaque, nostrum quisquam suscipit alias enim veniam ipsam consequatur quas odio quia? Earum, sequi distinctio laboriosam ut explicabo quam iste vero facere!
		</p>
	<a href="<%= sites_path %>">Site index</a>
</div>

	
</div>

app/views/sites/_index.html.erb
<h1 style="text-align:center">
	<span class="CheapNewYorkLogo">Cheap
	</span> New York <span class="CheapNewYorkLogoT">!</span>
</h1>

<br>
<form action="<%= sites_zipsearch_path %>" class="form-horizontal container" role="form"  method="POST">
	<div class="form-group col-xl-3">
		<div class="col-sm-3">
			<input type="hidden" class="form-control" name="_method" value="POST">
		    <label class="control-label" for="language">Zipcode search</label>
			<input type="text" class="form-control"  name="zipcode">
			<%= token_tag :authenticity_token %>
			<div>
				<input type="submit" class="form-control" value="Submit">
			</div>
		</div>
	</div>
</form>

<br><br>
<table id="myTable" class="tablesorter table-hover table">
	<thead>
		<tr>
			<th class="col-sm-1">Cost</th>
			<th class="col-sm-2">Name</th>
			<th class="col-sm-2">Address</th>
			<th class="col-sm-1">Zip</th>
			<th class="col-sm-1">Rating</th>
			<th class="col-sm-10">Reviews</th>
		</tr>
	</thead>
	<tbody>
		<% @sites.each do |site|  %>
			<tr>
				<td><%= site.cost %></td>
				<td><%= site.name %></td>
				<td>
					<a href="http://maps.google.com/?q=<%=site.address%>,<%=site.zipcode%>" target="_GoogleMap">
						<%= site.address %>
					</a>
				</td>
				<td><%= site.zipcode %></td>
 				<% if site.respond_to?(:image_url) %>
					<td><img src="<%= site.image_url %>"></td>
				<% else %>
					<% sum = 0 %>
					<% site.reviews.each do |review| %>
						<% sum += review.rating %>
					<% end %>
					<% unless(sum == 0) %>
						<td>
							<% weighted_rating = sum/site.reviews.size %>
							<% (weighted_rating.to_i).times do |x| %>&#9733;<% end %>
							<% if ((weighted_rating - weighted_rating.floor) > 0) %>&frac12;<%end %>
						</td>
					<% else %>
						<td>Unrated</td>
					<% end %>
				<% end %>
				<td>
					<% site.reviews.each_with_index do |review, index| %>
					<ul style="list-style: none; padding-left:0;">
						<% if review.respond_to?(:rating) %>
						<li>
							<% (review.rating.to_i).times do |x| %>&#9733;<% end %>

							<% if ((review.rating - review.rating.floor) > 0) %>
							&frac12;
							<%end %>
							<%= review.written_text %> 
							<%= link_to 'EDIT', edit_site_review_path(site, review), :method => :get %> 
							<%= link_to 'DELETE', site_review_path(site, review), :method => :delete %>
						</li>	
						<% else %>
						<li>
							<img src="<%= review[2] %>"><%= review[1] %>
						</li>
						<hr>
						<% end %>
					</ul>
					<% end %>

					<% if site.is_a?(YelpApi::YelpSite) == true %>

					<a href="<%= site.url %>" target="_YelpWindow">Site on Yelp</a>
					<% else %>
					<a href="<%= new_site_review_path(site) %>">
						<% if site.reviews.size == 0 %>
						Write the first review!
						<% else %>
						Write a Review
						<% end %>
					</a>

					<% end %>

				</td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/sites/index.html.erb
<%= render partial: "index" %>

app/views/sites/show.html.erb
<br><br>
<table id="myTable" class="tablesorter table-hover table">
	<thead>
		<tr>
			<th class="col-sm-1">Cost</th>
			<th class="col-sm-2">Name</th>
			<th class="col-sm-2">Address</th>
			<th class="col-sm-1">Zip</th>
			<th class="col-sm-1">Rating</th>
			<th class="col-sm-10">Reviews</th>
		</tr>
	</thead>
	<tbody>
			<tr>
				<td><%= @site.cost %></td>
				<td><%= @site.name %></td>
				<td>
					<a href="http://maps.google.com/?q=<%=@site.address%>,<%=@site.zipcode%>" target="_GoogleMap">
						<%= @site.address %>
					</a>
				</td>
				<td><%= @site.zipcode %></td>
 				<% if @site.respond_to?(:image_url) %>
					<td><img src="<%= @site.image_url %>"></td>
				<% else %>
					<% sum = 0 %>
					<% @site.reviews.each do |review| %>
						<% sum += review.rating %>
					<% end %>
					<% unless(sum == 0) %>
						<td>
							<% weighted_rating = sum/@site.reviews.size %>
							<% (weighted_rating.to_i).times do |x| %>&#9733;<% end %>
							<% if ((weighted_rating - weighted_rating.floor) > 0) %>&frac12;<%end %>
						</td>
					<% else %>
						<td>Unrated</td>
					<% end %>
				<% end %>
				<td>
					<% @site.reviews.each_with_index do |review, index| %>
					<ul style="list-style: none; padding-left:0;">
						<% if review.respond_to?(:rating) %>
						<li>
							<% (review.rating.to_i).times do |x| %>&#9733;<% end %>

							<% if ((review.rating - review.rating.floor) > 0) %>
							&frac12;
							<%end %>
							<%= review.written_text %> 
							<%= link_to 'EDIT', edit_site_review_path(@site, review), :method => :get %> 
							<%= link_to 'DELETE', site_review_path(@site, review), :method => :delete %>
						</li>	
						<% else %>
						<li>
							<img src="<%= review[2] %>"><%= review[1] %>
						</li>
						<hr>
						<% end %>
					</ul>
					<% end %>

					<% if @site.is_a?(YelpApi::YelpSite) == true %>

					<a href="<%= @site.url %>" target="_YelpWindow">Site on Yelp</a>
					<% else %>
					<a href="<%= new_site_review_path(@site) %>">
						<% if @site.reviews.size == 0 %>
						Write the first review!
						<% else %>
						Write a Review
						<% end %>
					</a>

					<% end %>

				</td>
			</tr>
	</tbody>
</table>

app/views/sites/splash.html.erb
<!-- <h1 style="text-align:center">
	<span class="CheapNewYorkLogo">Cheap
	</span> New York <span class="CheapNewYorkLogoT">!</span>
</h1>

 -->

 <img class="SpashImage" src="assets/CheapNewYorkSplash.png">

<script>
	$(function(){
		setTimeout(function(){
			window.location="/";
		},5000)
	})
</script>

app/views/sites/zipsearch.html.erb
<%= render partial: "index" %>